# Generated by Django 3.1.2 on 2021-03-06 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Event_images')),
                ('EventName', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('EventDescription', models.TextField(max_length=400)),
                ('likes', models.ManyToManyField(related_name='event_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
